---
version: 2
jobs:
 build:
  docker:
    - image: circleci/node
  steps:
    - checkout

    - add_ssh_keys:
            fingerprints:
                    - "67:e2:13:15:a6:b2:b7:7b:60:60:50:80:ef:ba:98:c8"
    - run:
            name: Keyscan deploy host
            command: ssh-keyscan -H hitman959.devops.srwx.net | sudo tee ~/.ssh/known_hosts

    - run:  echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/ansible-ubuntu-ansible-trusty.list
    - run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 
    - run: sudo apt-get update -y
    - run: sudo apt-get install ansible -y
    - run: ansible-galaxy install ansistrano.deploy ansistrano.rollback
    - run: ansible-playbook -i .cd/hosts .cd/deploy.yml
