---
version: 2
jobs:
 build:
  docker:
    - image: circleci/node
  steps:
    - checkout
    - run:
       name: Install ansible
       command: echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/ansible-ubuntu-ansible-trusty.list\
                 && sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367\
                 && sudo apt update\
                 && sudo apt-get install ansible -y

    - run:
       name: Install Ansistrano
       command: 'sudo ansible-galaxy install ansistrano.deploy ansistrano.rollback'
    - run:
       name: deploy jarvis
       command: 'ansible-playbook -i .cd/hosts .cd/deploy.yml'
