---
version: 2
jobs:
 build:
  docker:
    - image: circleci/node-bionic
  steps:
    - checkout
    - run:
       name: Install ansible
       command: 'sudo apt-get update -y && sudo apt-get install software-properties-common -y && sudo apt-add-repository --yes --update ppa:ansible/ansible && apt-get install ansible -y'

    - run:
       name: Install Ansistrano
       command: 'ansible-galaxy install ansistrano.deploy ansistrano.rollback'
    - run:
       name: deploy jarvis
       command: 'ansible-playbook -i .cd/hosts .cd/deploy.yml'
