---
version: 2
jobs:
 build:
  docker:
    - image: circleci/node
  steps:
    - checkout
    - run:
       name: Install ansible
       command: 'sudo apt-get update && sudo apt-get install software-properties-common && sudo apt-add-repository --yes --update ppa:ansible/ansible && sudo  apt-get install ansible'

    - run:
       name: Install Ansistrano
       command: 'sudo ansible-galaxy install ansistrano.deploy ansistrano.rollback'
    - run:
       name: deploy jarvis
       command: 'ansible-playbook -i .cd/hosts .cd/deploy.yml'
